#! /bin/sh
# 
# mtdblock4 is mounted on /opt and exported via nfs.
# this method is far more stable than via  mass_storage gadget.
#
#  

case "$1" in
	start)	mount -t ext4 /dev/mtdblock4 /opt
		;;
	stop)	sync
		umount /opt
		;;
	*)
		exit 1
		;;
esac
