#!/bin/bash
modprobe libcomposite
mount -t configfs none /sys/kernel/config
mkdir /sys/kernel/config/usb_gadget/g1
cd /sys/kernel/config/usb_gadget/g1/
mkdir configs/c.1
mkdir functions/mass_storage.0
echo /dev/mtdblock4 >  /sys/kernel/config/usb_gadget/g1/functions/mass_storage.0/lun.0/file 
cd /sys/kernel/config/usb_gadget/g1/
ln -s functions/mass_storage.0 configs/c.1
echo "ci_hdrc.0" > UDC 
exit 0
