#!/usr/bin/env bash
echo "configuring  rootfs"
cat > output/target/etc/exports <<EOF
/opt     *(rw,sync,no_subtree_check,no_root_squash)
EOF
# remove proc mount entry (already done before switch_root)
sed -i '/si0/d' output/target/etc/inittab
# remove remount rw entry too
sed -i '/si1/d' output/target/etc/inittab
rm output/target/etc/dropbear
mkdir output/target/etc/dropbear
cp system/dropbear_ecdsa_host_key output/target/etc/dropbear/
cd output/target/usr/share/terminfo/x/
if [ ! -L xterm-256color ]; then
	ln -s xterm-color xterm-256color
fi
cd -
