#!/usr/bin/env bash
echo "configuring  rootfs"
cat > output/target/etc/exports <<EOF
/opt     *(rw,sync,no_subtree_check,no_root_squash)
EOF
# remove entries from inittab 
sed -i '/si0/d' output/target/etc/inittab
sed -i '/si1/d' output/target/etc/inittab
sed -i '/shd1/d' output/target/etc/inittab
sed -i '/shd2/d' output/target/etc/inittab



rm -rf output/target/etc/dropbear
mkdir output/target/etc/dropbear
cp system/dropbear_ecdsa_host_key output/target/etc/dropbear/
cd output/target/usr/share/terminfo/x/
if [ ! -L xterm-256color ]; then
	ln -s xterm-color xterm-256color
fi
cd -

# add brcm firmware to target
cp -a system/firmware output/target/lib/


rm -rf output/target/etc/init.d/S90pwm
