#!/bin/sh
echo "cleaning partition table"
dd if=/dev/zero of=/dev/mmcblk1 bs=1M count=10
echo "creating new partition table"
printf "2048,+2G,83\n,,83" | sfdisk /dev/mmcblk1
sleep 2 
echo "creating filesystems .."
mkfs.ext4 /dev/mmcblk1p1
# dont do this when testing
# mkfs.ext4 /dev/mmcblk1p2
mount /dev/mmcblk1p1 /mnt
cd /mnt
wget http://10.1.30.30:8000/src/VAL100/val100.tar
wget http://10.1.30.30:8000/src/VAL100/MD5SUM -O md5SUM
if  md5sum -c md5SUM ; then 
	tar -xf val100.tar
	rm *
	mv val100/* .
	rm -rf val100
	md5sum * > /tmp/MD5SUM
	mv /tmp/MD5SUM .
	cd ~
	sync
	umount /mnt
	echo "all done, reboot to new system"
else
	echo "package checksum failed.. cannot proceed"
fi
